// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKIJG7o4mDirT7VIJu2hDXABkQ4HKZTRI',
    appId: '1:85323614026:web:cfb0c6bab2c2c774f263b3',
    messagingSenderId: '85323614026',
    projectId: 'my-wallet001',
    authDomain: 'my-wallet001.firebaseapp.com',
    storageBucket: 'my-wallet001.firebasestorage.app',
    measurementId: 'G-B69FDB90WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXPCuVPSZgyfPNtkVJj2jr5FnvLrYnIaI',
    appId: '1:85323614026:android:63f87eda66740fe6f263b3',
    messagingSenderId: '85323614026',
    projectId: 'my-wallet001',
    storageBucket: 'my-wallet001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr3PeNf_OWHrSrZ342rSpDnDgE_YGnA8M',
    appId: '1:85323614026:ios:11a9ae419a994d14f263b3',
    messagingSenderId: '85323614026',
    projectId: 'my-wallet001',
    storageBucket: 'my-wallet001.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr3PeNf_OWHrSrZ342rSpDnDgE_YGnA8M',
    appId: '1:85323614026:ios:11a9ae419a994d14f263b3',
    messagingSenderId: '85323614026',
    projectId: 'my-wallet001',
    storageBucket: 'my-wallet001.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKIJG7o4mDirT7VIJu2hDXABkQ4HKZTRI',
    appId: '1:85323614026:web:cfb0c6bab2c2c774f263b3',
    messagingSenderId: '85323614026',
    projectId: 'my-wallet001',
    authDomain: 'my-wallet001.firebaseapp.com',
    storageBucket: 'my-wallet001.firebasestorage.app',
    measurementId: 'G-B69FDB90WB',
  );

}